Dz06 02 bgimage
js-tasks-ru/htmlcss-20220120_yurgn13 pull request #13
Opened 2022-02-09 18:16 UTC by YURgn

2022-02-09 18:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-10 15:10 UTC, GSemikozov requested changes

2022-02-10 15:10 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +    @media screen and (min-width: 768px) and (max-width:1024px)
следует избегать совпадения точки разрыва одновременно у min-width и max-width. В данном случае лучше выбрать один подход и использовать либо только min-width, либо только max-width

2022-02-10 16:14 UTC, YURgn commented on 06-lection4/02-background-image/background-image.css
> +    @media screen and (min-width: 768px) and (max-width:1024px)
ok

2022-02-13 21:04 UTC, GSemikozov approved these changes

2022-02-13 21:04 UTC, merged