solution for dz07-01-checkbox
js-tasks-ru/htmlcss-20220120_yurgn13 pull request #17
Opened 2022-02-11 16:21 UTC by YURgn

при visibility: hidden не фокусируется элемент, поэтому делал через opacity.
при фокусе подчеркивается текст

2022-02-11 16:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-13 21:09 UTC, GSemikozov requested changes

2022-02-13 21:09 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +padding: 2px;
по дизайну кажется правильным не ставить здесь паддинг

2022-02-13 21:09 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +opacity: 0;
насчет visibility кстати хорошо что подмечено

2022-02-13 21:09 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +border-bottom: 2px solid var(--white);
лучше transparent

2022-02-13 21:09 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    border-bottom: 2px solid var(--grey-2);
и тут меняем только border-color

2022-02-14 12:32 UTC, YURgn commented on 07-lection5/01-checkbox/checkbox.css
> +padding: 2px;
если паддинг не поставить, то не будет выдержано расстояние от внешней рамки до переключателя

2022-02-14 12:33 UTC, YURgn commented on 07-lection5/01-checkbox/checkbox.css
> +opacity: 0;
спасибо

2022-02-14 12:39 UTC, YURgn commented on 07-lection5/01-checkbox/checkbox.css
> +padding: 2px;
перепутал с toggle) да тут не нужно

2022-02-14 12:42 UTC, YURgn commented on 07-lection5/01-checkbox/checkbox.css
> +border-bottom: 2px solid var(--white);
не знал про этот параметр, спасибо

2022-02-14 21:16 UTC, GSemikozov approved these changes

2022-02-14 21:16 UTC, merged