Dz09 burger menu
js-tasks-ru/htmlcss-20220120_yurgn13 pull request #21
Opened 2022-02-23 17:30 UTC by YURgn

2022-02-23 17:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-24 10:56 UTC, GSemikozov requested changes

2022-02-24 10:56 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-open{
это не часть бургер-меню, это кнопка в хедере. В нашем случае тут достаточно использовать обычную кнопку для вызова меню

2022-02-24 10:56 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__toggletheme{
лучше реализовать как отдельный компонент

2022-02-24 10:56 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__nav a{
.burger-menu__nav a -> .burger-menu__nav-item

2022-02-24 17:33 UTC, YURgn commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__nav a{
ok

2022-02-24 17:34 UTC, YURgn commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__toggletheme{
toggler и сделан отдельным компонентом, а это контейнер для него.

2022-02-24 17:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-24 19:14 UTC, GSemikozov requested changes

2022-02-24 19:14 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.button-menubrg{
но это ведь все равно часть хедера) или просто другой блок) ему не место в файле описания .burger-menu

2022-02-25 16:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-25 16:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-26 11:52 UTC, GSemikozov approved these changes

2022-02-26 11:52 UTC, merged