add solution for 03-lection\01-button
js-tasks-ru/htmlcss-20220120_yurgn13 pull request #3
Opened 2022-01-26 20:34 UTC by YURgn

add solution for 03-lection\01-button

2022-01-26 20:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-26 23:48 UTC, GSemikozov requested changes

2022-01-26 23:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.main {
в файле стилей блока могут быть лишь стили для этого блока и его элементов и модификаторов) следовательно, другие блоки - тут .main и его элемент .main__button - уносим в другое место. С учетом того что это просто вспомогательные стили - их можно оформлять прямо на хтмл странице в теге style

2022-01-26 23:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  .button__button {
это просто .button. Соответственно - ниже везде надо поправить)

2022-01-26 23:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  .button__button--primary:disabled {
disabled у всех типов одинаковый, лучше использовать отдельный модификатор .button_disabled

2022-01-26 23:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
такой курсор можно задать по умолчанию на .button

2022-01-26 23:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
можно указать сразу на .button

2022-01-26 23:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: var(--grey-4);
много лишнего дублируем, меняется лишь border-color

2022-01-29 14:29 UTC, YURgn commented on 03-lection1/01-button/button.css
> +.main {
fix

2022-01-29 14:29 UTC, YURgn commented on 03-lection1/01-button/button.css
> +  .button__button {
fix

2022-01-29 14:29 UTC, YURgn commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
fix

2022-01-29 14:30 UTC, YURgn commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
fix

2022-01-29 14:30 UTC, YURgn commented on 03-lection1/01-button/button.css
> +    color: var(--grey-4);
fix

2022-01-29 14:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-30 15:30 UTC, GSemikozov approved these changes

2022-01-30 15:31 UTC, merged