solution dz-card
js-tasks-ru/htmlcss-20220120_yurgn13 pull request #9
Opened 2022-02-04 19:37 UTC by YURgn

2022-02-04 19:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-04 19:53 UTC, GSemikozov requested changes

2022-02-04 19:53 UTC, GSemikozov commented on components/card/card.css
> +flex: 1 1 25%;
а для чего именно так?

2022-02-05 09:20 UTC, YURgn commented on components/card/card.css
> +flex: 1 1 25%;
исправил

2022-02-05 09:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-07 20:10 UTC, GSemikozov approved these changes

2022-02-07 20:10 UTC, merged